In [1]:
my_list = [1,2,3]

In [2]:
my_list

[1, 2, 3]

In [3]:
import numpy as np

In [8]:
arr = np.array(my_mat)

In [9]:
arr 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [14]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [15]:
np.zeros(3)

array([0., 0., 0.])

In [20]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [23]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [24]:
np.random.rand(3,3)

array([[0.63291961, 0.05839189, 0.82528648],
       [0.32785168, 0.49748866, 0.45486962],
       [0.27605269, 0.95086364, 0.07563495]])

In [27]:
np.random.randint(1,10)

4

In [29]:
ranarr = np.arange(25)

In [30]:
ranarr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [34]:
kkk = np.reshape(ranarr,(5,5))

In [39]:
kkk.max()

24

In [62]:
arr = np.arange(0,11)

In [41]:
arr[1]

1

In [43]:
arr[:4]

array([0, 1, 2, 3])

In [44]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
arr[1:3] = 10

In [46]:
arr

array([ 0, 10, 10,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
slice_of_arr = arr[0:6]

In [49]:
slice_of_arr[:] = 99 

In [50]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [64]:
arr_2d = np.arange(5,46,5).reshape(3,3)

In [65]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [60]:
arr_2d[0]

array([ 5, 10, 15])

In [63]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [72]:
arr = np.arange(0,11)

In [67]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [71]:
arr + 1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [73]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [74]:
arr.max()

10

In [75]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [76]:
x = [1,2,3]

In [77]:
import pandas as pd

In [89]:
labels = ['a','b','c']
my_data = [10,20,30]
arr = np.array(my_data)
d = {'a':10,'b':20,'c':30}

In [80]:
pd.Series(data = my_data)

0    10
1    20
2    30
dtype: int64

In [82]:
pd.Series(data=my_data,index=labels)

a    10
b    20
c    30
dtype: int64

In [84]:
pd.Series(my_data,labels)

a    10
b    20
c    30
dtype: int64

In [85]:
ser1 = pd.Series([1,2,3,4],['USA','Germany','USSR','Japan'])

In [86]:
ser1

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [87]:
np.random.seed(101)

In [120]:
df = pd.DataFrame(np.random.randn(5,4),['A','B','C','D','E'],['W','X','Y','Z'])

In [121]:
df

W         X         Y         Z
A -0.993263  0.196800 -1.136645  0.000366
B  1.025984 -0.156598 -0.031579  0.649826
C  2.154846 -0.610259 -0.755325 -0.346419
D  0.147027 -0.479448  0.558769  1.024810
E -0.925874  1.862864 -1.133817  0.610478

In [100]:
type(df['W'])

pandas.core.series.Series

In [104]:
df['W']

A    0.302665
B   -0.134841
C    0.807706
D   -0.497104
E   -0.116773
Name: W, dtype: float64

In [105]:
df['new'] = df['W'] + df['Y']

In [115]:
df.drop('new',axis =  1, inplace=True)

In [114]:
df.iloc[1:3,3]

B    0.184502
C    0.329646
Name: Z, dtype: float64

In [116]:
df > 0

W      X      Y      Z
A   True   True  False  False
B  False   True   True   True
C   True   True   True   True
D  False  False  False   True
E  False   True   True   True

In [118]:
df[df > 0] = 1

In [119]:
df

W        X         Y         Z
A  1.000000  1.00000 -1.706086 -1.159119
B -0.134841  1.00000  1.000000  1.000000
C  1.000000  1.00000  1.000000  1.000000
D -0.497104 -0.75407 -0.943406  1.000000
E -0.116773  1.00000  1.000000  1.000000

In [122]:
df['W'] > 0

A    False
B     True
C     True
D     True
E    False
Name: W, dtype: bool

In [123]:
df[df['W']>0]

W         X         Y         Z
B  1.025984 -0.156598 -0.031579  0.649826
C  2.154846 -0.610259 -0.755325 -0.346419
D  0.147027 -0.479448  0.558769  1.024810

In [124]:
df

W         X         Y         Z
A -0.993263  0.196800 -1.136645  0.000366
B  1.025984 -0.156598 -0.031579  0.649826
C  2.154846 -0.610259 -0.755325 -0.346419
D  0.147027 -0.479448  0.558769  1.024810
E -0.925874  1.862864 -1.133817  0.610478

In [125]:
df[df['Z']<0]

W         X         Y         Z
C  2.154846 -0.610259 -0.755325 -0.346419

In [128]:
df[df['W']>0][['Y','X']]

Y         X
B -0.031579 -0.156598
C -0.755325 -0.610259
D  0.558769 -0.479448

In [129]:
df.reset_index()

index         W         X         Y         Z
0     A -0.993263  0.196800 -1.136645  0.000366
1     B  1.025984 -0.156598 -0.031579  0.649826
2     C  2.154846 -0.610259 -0.755325 -0.346419
3     D  0.147027 -0.479448  0.558769  1.024810
4     E -0.925874  1.862864 -1.133817  0.610478

In [130]:
newind = 'CA NY WY OR CO'.split()

In [131]:
newind

['CA', 'NY', 'WY', 'OR', 'CO']

In [133]:
df['States'] = newind

In [134]:
df.set_index('States')

W         X         Y         Z
States                                        
CA     -0.993263  0.196800 -1.136645  0.000366
NY      1.025984 -0.156598 -0.031579  0.649826
WY      2.154846 -0.610259 -0.755325 -0.346419
OR      0.147027 -0.479448  0.558769  1.024810
CO     -0.925874  1.862864 -1.133817  0.610478